version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PVZ-service
    ports:
      - "8080:8080"
    environment:
      # Параметры подключения к базе данных
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydb
      # Параметры подключения к Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Порт сервера
      SERVER_PORT: 8080
      # Секретный ключ для jwt
      JWT_SECRET_KEY: mySuperSecretKey123
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
