version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PVZ-service-test
    ports:
      - "8081:8081"  # Изменён порт, чтобы не конфликтовал с продом
    environment:
      # Подключение к тестовой базе данных
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpassword
      DATABASE_NAME: testdb
      # Порт сервера
      SERVER_PORT: 8081
      # Тестовый JWT ключ
      JWT_SECRET_KEY: testSecretKey456
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test-network
  db:
    image: postgres:15-alpine
    container_name: postgres-test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  test-postgres-data:
